backend:
  name: git-gateway
  branch: main

media_folder: "uploads" # Folder where uploaded images/files go in your repo
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "index.html"
        label: "Home & About"
        name: "home"
        fields:
          - label: "Hero Title"
            name: "hero_title"
            widget: "string"
            hint: "Main heading in the hero section"

          - label: "Hero Subtitle"
            name: "hero_subtitle"
            widget: "text"
            hint: "Text below the hero title"

          - label: "About Section Text"
            name: "about_content"
            widget: "text"
            hint: "Main text for the About Us section"
